### ISSUE TITLE
I had an error when command "learn" before doing anything

### ISSUE THREAD

**Issue by aabuauf** [learn-co-curriculum/activerecord-crud#66] opened 2019-08-17 00:49 UTC
I had an error when I run "learn" in the terminal and I got error. It was fixed when i changed Gemfile  to be. I changed 'sqlite3', '~>1.3.6' to be 'sqlite3', '~>1.4'.

**Comment by sgharms** [comment] 2019-08-19 11:00
This issue (and #67) are caused by the lab using ActiveRecord 6.0 versus 5.2.

I have checked out this lab after specifying which version to use and it works.

If you've not gotten the lab working yet, try again. If, otherwise, you're working OK now, we'll close this issue.

**Comment by sgharms** [comment] 2019-08-19 11:02
Here's my run of `learn`

```text
  9) Movie basic CRUD creating can be instantiated and then saved
     Failure/Error: raise "Replace __ with test code."

     RuntimeError:
       Replace __ with test code.
     # ./spec/spec_helper.rb:28:in `__'
     # ./app/movies_controller.rb:9:in `can_be_instantiated_and_then_saved'
     # ./spec/models/movie_spec.rb:63:in `block (4 levels) in <top (required)>'
```

**Comment by sgharms** [comment] 2019-08-21 15:45
@aabuauf 

I'm going to close this case since we've not heard back from you. If you find you still have an issue here, let me know and we'll re-open!

Steven

**Closed by sgharms** 2019-08-21 15:45 UTC
